### ISSUE TITLE
Add categories in backend and create pie chart of spending by category.

### ISSUE THREAD

**Issue by aviflombaum** [matthewpaulmcgowan/money-management#2]
If an item belongs to a category and a category has many items then you can make a pie chart of spending by category. You should update the forms to accept a category name and create the category on the backend if it's new otherwise find it and add that as the associated category for the new item. Try to use `category_name=` as a custom writer on your `Item` model to do that to pass `params` from angular into the mass assignment of an Item to trigger the writer, i.e, `Item.new(:category_name => "Entertainment", :name => "Concert", :amount => "100")`.

Then add a chart plugin with angular to visual spending by category. Would be cool if the chart was a filter too - so when I click on the % of spending that is "Entertainment", it filters the list in view to just those expenses.

**Comment by aviflombaum** [comment]
Hey Matt, let me know how this one is going, if you want to catchup for 10-15 minutes let me know. Great job on the other issues.

**Comment by matthewpaulmcgowan** [comment]
Hey Avi, I think I have the back end figured out and the chart is rendering correctly. I still need to add the filters and am looking to make it easier to add to categories you have previously used.

**Comment by aviflombaum** [comment]
Awesome!!! Can't wait to see it! Ping me when you're ready, so excited for you! :metal:

**Comment by matthewpaulmcgowan** [comment]
Hi @aviflombaum ,  
I've finished up adding the chart to my app!
